<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Carrito de la compra</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="css/home.css">
        <?php
        if (!empty($logedFail)) {
            echo $abrirModal;
        }
        ?>
    </head>
    <!-- Barra de navegacion -->
<?php require_once("views/header.phtml"); ?>
    <body class="bg-secondary">
        <div class="container">
            <div class="row">
                <div class="col-8 bg-light mt-3">
                    <h2>
                        <th scope="col"><strong>(<?php echo count($_SESSION['cart'])?>)</strong> Artículos <strong>en tu cest</strong>a</th>
                    </h2>
                    <table class="table table-hover bg-white ">
                <thead>
                    <tr class="">
                        <th scope="col"></th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Unidades</th>
                        <th scope="col">Precio</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if (!empty($_SESSION['cart'])) {
                        foreach ($_SESSION['cart'] as $carrito) {
                            ?>
                            <tr>
                                <td scope="row" class="imgCartView"><img class="img-fluid" src="<?php echo $carrito['image'] ?>" alt="<?php echo $carrito['name'] ?>"/></td>
                                <td><small><strong><?php echo $carrito['name']?></strong></small></td>
                                <td class="text-center"><?php echo $carrito['numUnits']?></td>
                                <td><?php echo $carrito['price']?>€</td>
                                <td><a href="index.php?controller=cart&action=deleteFromCartView&product=<?php echo $carrito['id']?>"><button class="btn btn-danger  fa fa-close"></button></a></td>
                            </tr>

    <?php }
} ?>
                </tbody>
            </table>
                </div>
                <div class="col-4">
                    
                </div>
            </div>
            
        </div>  

    </body>
    <footer class="mt-4 ">
        <div class="bg-primary py-3">
            <div class="container">
                <div class="row">
                    <div class="col-md-7">
                        <div class="row py-0">
                            <div class="col-sm-1 hidden-md-down">
                                <a class="bg-circle bg-info" href="#">
                                    <i class="fa fa-2x fa-fw fa-address-card" aria-hidden="true "></i>
                                </a>
                            </div>
                            <div class="col-sm-11 text-white">
                                <div><h4>  Contacto</h4>
                                    <p>   <span class="header-font">EGC</span>omponentes.com</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="d-inline-block">
                            <div class="bg-circle-outline d-inline-block" style="background-color:#3b5998">
                                <a href="https://www.facebook.com/"><i class="fa fa-2x fa-fw fa-facebook text-white"></i>
                                </a>
                            </div>
                            <div class="bg-circle-outline d-inline-block" style="background-color:#4099FF">
                                <a href="https://twitter.com/">
                                    <i class="fa fa-2x fa-fw fa-twitter text-white"></i></a>
                            </div>

                            <div class="bg-circle-outline d-inline-block" style="background-color:#0077B5">
                                <a href="https://www.linkedin.com/company/">
                                    <i class="fa fa-2x fa-fw fa-linkedin text-white"></i></a>
                            </div>
                            <div class="bg-circle-outline d-inline-block" style="background-color:#d34836">
                                <a href="https://www.google.com/">
                                    <i class="fa fa-2x fa-fw fa-google text-white"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/.footer-->
    <p class="text-center"> Copyright <i class="fa fa-copyright" aria-hidden="true"></i>
        EGComponentes 2018. Todos los derechos reservados. </p>
    <!--/.footer-bottom-->
    <div class="myModal">
<?php include("views/login_view.phtml"); ?>
    </div>

</html>