<!DOCTYPE html>
<html>
    <head>
        <title>Añadir categoria</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="css/home.css">
    </head>
    <!-- Barra de navegacion -->
    <?php require_once ("header.phtml"); ?>
    <body class="bg-secondary">
        <div class="container bg-light mt-4 vistaContainer">
            <form name="addProd" action="index.php?controller=categories&action=insert" method="post">
                <h1 class="text-center">Añadir categoria</h1>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Nombre</span>
                    </div>
                    <input type="text" class="form-control" name="nombre">
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="inputGroupSelect01">Categoria padre</label>
                    </div>
                    <select class="custom-select" id="parentcategory" name="parentcategory">
                        <option value="NULL" selected>Elige...</option>
                        <?php foreach ($datos as $dato) { ?>
                            <option value="<?php echo $dato['ID'] ?>"><?php echo $dato['NAME'] ?></option>
                        <?php } ?>
                    </select>
                </div>
                <button class="btn btn-lg btn-dark" type="submit">Añadir</button>
            </form>
        </div>
    </body>
    <?php require_once ("footer.phtml"); ?>
</html>
