
<?php
if (isset($_SESSION['usuario'])) {
    if ($_SESSION['usuario'] == "admin") {
        ?>
        <footer class="mt-4">
            <div class="bg-danger py-3">
                <div class="container">
                    <div class="row">
                        <div class="col-md-7">
                            <div class="row py-0">
                                <div class="col-sm-1 hidden-md-down">
                                    <a class="bg-circle bg-info" href="#">
                                        <i class="fa fa-2x fa-fw fa-address-card" aria-hidden="true "></i>
                                    </a>
                                </div>
                                <div class="col-sm-11 text-white">
                                    <div><h4>  Contacto</h4>
                                        <p>   <span class="header-font">EGC</span>omponentes.com</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="d-inline-block">
                                <div class="bg-circle-outline d-inline-block" style="background-color:#3b5998">
                                    <a href="https://www.facebook.com/"><i class="fa fa-2x fa-fw fa-facebook text-white"></i>
                                    </a>
                                </div>
                                <div class="bg-circle-outline d-inline-block" style="background-color:#4099FF">
                                    <a href="https://twitter.com/">
                                        <i class="fa fa-2x fa-fw fa-twitter text-white"></i></a>
                                </div>

                                <div class="bg-circle-outline d-inline-block" style="background-color:#0077B5">
                                    <a href="https://www.linkedin.com/company/">
                                        <i class="fa fa-2x fa-fw fa-linkedin text-white"></i></a>
                                </div>
                                <div class="bg-circle-outline d-inline-block" style="background-color:#d34836">
                                    <a href="https://www.google.com/">
                                        <i class="fa fa-2x fa-fw fa-google text-white"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    <?php } else { ?>
        <footer class="mt-4">
            <div class="bg-primary py-3">
                <div class="container">
                    <div class="row">
                        <div class="col-md-7">
                            <div class="row py-0">
                                <div class="col-sm-1 hidden-md-down">
                                    <a class="bg-circle bg-info" href="#">
                                        <i class="fa fa-2x fa-fw fa-address-card" aria-hidden="true "></i>
                                    </a>
                                </div>
                                <div class="col-sm-11 text-white">
                                    <div><h4>  Contacto</h4>
                                        <p>   <span class="header-font">EGC</span>omponentes.com</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="d-inline-block">
                                <div class="bg-circle-outline d-inline-block" style="background-color:#3b5998">
                                    <a href="https://www.facebook.com/"><i class="fa fa-2x fa-fw fa-facebook text-white"></i>
                                    </a>
                                </div>
                                <div class="bg-circle-outline d-inline-block" style="background-color:#4099FF">
                                    <a href="https://twitter.com/">
                                        <i class="fa fa-2x fa-fw fa-twitter text-white"></i></a>
                                </div>

                                <div class="bg-circle-outline d-inline-block" style="background-color:#0077B5">
                                    <a href="https://www.linkedin.com/company/">
                                        <i class="fa fa-2x fa-fw fa-linkedin text-white"></i></a>
                                </div>
                                <div class="bg-circle-outline d-inline-block" style="background-color:#d34836">
                                    <a href="https://www.google.com/">
                                        <i class="fa fa-2x fa-fw fa-google text-white"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <?php }} else{ ?>
        <footer class="mt-4">
            <div class="bg-primary py-3">
                <div class="container">
                    <div class="row">
                        <div class="col-md-7">
                            <div class="row py-0">
                                <div class="col-sm-1 hidden-md-down">
                                    <a class="bg-circle bg-info" href="#">
                                        <i class="fa fa-2x fa-fw fa-address-card" aria-hidden="true "></i>
                                    </a>
                                </div>
                                <div class="col-sm-11 text-white">
                                    <div><h4>  Contacto</h4>
                                        <p>   <span class="header-font">EGC</span>omponentes.com</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="d-inline-block">
                                <div class="bg-circle-outline d-inline-block" style="background-color:#3b5998">
                                    <a href="https://www.facebook.com/"><i class="fa fa-2x fa-fw fa-facebook text-white"></i>
                                    </a>
                                </div>
                                <div class="bg-circle-outline d-inline-block" style="background-color:#4099FF">
                                    <a href="https://twitter.com/">
                                        <i class="fa fa-2x fa-fw fa-twitter text-white"></i></a>
                                </div>

                                <div class="bg-circle-outline d-inline-block" style="background-color:#0077B5">
                                    <a href="https://www.linkedin.com/company/">
                                        <i class="fa fa-2x fa-fw fa-linkedin text-white"></i></a>
                                </div>
                                <div class="bg-circle-outline d-inline-block" style="background-color:#d34836">
                                    <a href="https://www.google.com/">
                                        <i class="fa fa-2x fa-fw fa-google text-white"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    <?php } ?>
    <!--/.footer-->
    <p class="text-center"> Copyright <i class="fa fa-copyright" aria-hidden="true"></i>
        EGComponentes 2018. Todos los derechos reservados. </p>
    <!--/.footer-bottom-->
    <div class="myModal">
        <?php include("views/login_view.phtml"); ?>
</div>