<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title>Home</title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="css/home.css">
        <script src="views/filtros.js"></script>

    </head>
            <?php
        if (!empty($logedFail)) {
            echo $abrirModal;
        }
        ?>
    <!-- Barra de navegacion -->

    <body class="bg-secondary">
    <?php require_once("views/header.phtml"); ?>
        <!-- Carousel -->
        <div id="carousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner bg-dark py-1" role="listbox">
                <?php
                $cont = 0;
                foreach ($datosCar as $dato) {
                    ?>
                    <div class="carousel-item <?php if ($cont == 0) { ?> active <?php
                        $cont++;
                    }
                    ?>">
                        <img class="d-block img-fluid imgCarousel" src="<?php echo $dato["URL"] ?>" alt="First slide">
                        <div class="carousel-caption d-none d-md-block">
                            <h3><?php echo $dato["SHORTDESCRIPTION"] ?></h3>
                            <h4><span class="badge badge-danger"><?php echo $dato["DISCOUNTPERCENTAGE"] ?>%</span></h4>
                            <p>Por solo <?php echo $dato["PRECIOFINAL"] ?>€</p>
                        </div>
                    </div>
                <?php } ?>
            </div>
            <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <div class="container mt-2">
            <div class="row">
                <?php
                foreach ($orderedCategories as $id => $category) {
                    $catName = $category[0];
                    ?>
                    <div class="col-6 col-md-3 mb-2">
                        <div class="dropdown">
                            <button type="button" class=" btn btn-block dropdown-toggle text-muted" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <a class="text-light" href="#"><?php echo $catName; ?></a>
                            </button>
                            <div class="dropdown-menu " aria-labelledby="dropdownMenuButton" >

                                <?php
                                for ($i = 1; $i < count($category); $i++) {
//                                echo "<pre>".print_r($category, 1)."</pre>"; die;
                                    $idSubcategory = $category[$i]['ID'];
                                    $nameSubCategory = $category[$i]['NAME'];
                                    ?>
                                    <a class="dropdown-item" href="index.php?controller=products&action=viewCat&idSubcategory=<?php echo $idSubcategory ?>"><?php echo $nameSubCategory; ?></a>
                                    <?php
                                }
                                ?>
                            </div>

                        </div>
                    </div>
                    <?php
                }
                ?>
            </div>
        </div>
        <div class="container bg-secondary">
            <div class="row">
                <?php foreach ($datos as $dato) {
                    ?>
                    <div class="col-12 col-sm-6 col-md-4 col-xl-3">
                        <div class="card my-3">
                            <a href="index.php?controller=products&action=viewPage&id=<?php echo $dato['ID'] ?>">
                                <img class="card-img-top img-fluid zoom" src="<?php echo $dato['URL'] ?> " alt="Card image">
                            </a>
                            <div class="card-body">
                                <p class="card-title"><strong><?php echo $dato['SHORTDESCRIPTION'] ?> </strong></p>
                                <?php if (empty($dato['DISCOUNTPERCENTAGE'])) { ?>
                                    <p class="card-text text-center"><strong><?php echo $dato['PRICE']; ?>€</strong></p>
                                <?php } else { ?>
                                    <p class="card-text text-center">
                                        <span><strong><?php echo $dato['PRECIOFINAL']; ?>€</strong></span>
                                        <span class="text-muted"><small><s><?php echo $dato['PRICE']; ?>€</s></small></span>
                                        <span class="badge badge-danger"><?php echo $dato['DISCOUNTPERCENTAGE']; ?>%</span>
                                    </p>

                                <?php } ?>
                                <?php
                                if (isset($_SESSION['usuario'])) {
                                    if ($_SESSION['usuario'] == "admin") {
                                        ?>
                                        <div class="card-footer text-center">
                                            <small> <?php if ($dato['STOCK'] == 0) { ?>
                                                    <span style="color:red"> <?php echo "No quedan productos"; ?></span>
                                                </small>
                                            <?php } elseif ($dato['STOCK'] < 5) {
                                                ?>
                                                <span style="color:orange"> <?php echo "Quedan pocos en stock"; ?></span>
                                                </small>
                                               <?php } else { ?>
                                                <span style="color:green"> <?php echo "Hay productos en stock"; ?></span>
                                                </small>
                                            <?php } ?>
                                            <?php } else{ ?>
                                        <div class="card-footer text-center">
                                            <small> <?php if ($dato['STOCK'] == 0) { ?>
                                                    <span style="color:red"> <?php echo "No quedan productos"; ?></span>
                                                </small>
                                                <a href="index.php?controller=cart&action=addToCart&product=<?php echo $dato['ID'] ?>&productName=<?php echo $dato['SHORTDESCRIPTION'] ?>
                                                   &productPrice=<?php echo $dato['PRICE'] ?>&productImage=<?php echo $dato['URL'] ?>&productStock=<?php echo $dato['STOCK'] ?>&productPriceFinal=<?php echo $dato['PRECIOFINAL'] ?>" class="btn btn-primary disabled">Comprar</a>

                                            <?php } elseif ($dato['STOCK'] < 5) {
                                                ?>
                                                <span style="color:orange"> <?php echo "Quedan pocos en stock"; ?></span>
                                                </small>
                                                <a href="index.php?controller=cart&action=addToCart&product=<?php echo $dato['ID'] ?>&productName=<?php echo $dato['SHORTDESCRIPTION'] ?>
                                                   &productPrice=<?php echo $dato['PRICE'] ?>&productImage=<?php echo $dato['URL'] ?>&productStock=<?php echo $dato['STOCK'] ?>&productPriceFinal=<?php echo $dato['PRECIOFINAL'] ?>" class="btn btn-primary">Comprar</a>
                                               <?php } else { ?>
                                                <span style="color:green"> <?php echo "Hay productos en stock"; ?></span>
                                                </small>
                                                <a href="index.php?controller=cart&action=addToCart&product=<?php echo $dato['ID'] ?>&productName=<?php echo $dato['SHORTDESCRIPTION'] ?>
                                                   &productPrice=<?php echo $dato['PRICE'] ?>&productImage=<?php echo $dato['URL'] ?>&productStock=<?php echo $dato['STOCK'] ?>&productPriceFinal=<?php echo $dato['PRECIOFINAL'] ?>" class="btn btn-primary">Comprar</a>
                                            <?php } ?>
                                            <?php }} else{ ?>
                                        <div class="card-footer text-center">
                                            <small> <?php if ($dato['STOCK'] == 0) { ?>
                                                    <span style="color:red"> <?php echo "No quedan productos"; ?></span>
                                                </small>
                                                <a href="index.php?controller=cart&action=addToCart&product=<?php echo $dato['ID'] ?>&productName=<?php echo $dato['SHORTDESCRIPTION'] ?>
                                                   &productPrice=<?php echo $dato['PRICE'] ?>&productImage=<?php echo $dato['URL'] ?>&productStock=<?php echo $dato['STOCK'] ?>&productPriceFinal=<?php echo $dato['PRECIOFINAL'] ?>" class="btn btn-primary disabled">Comprar</a>

                                            <?php } elseif ($dato['STOCK'] < 5) {
                                                ?>
                                                <span style="color:orange"> <?php echo "Quedan pocos en stock"; ?></span>
                                                </small>
                                                <a href="index.php?controller=cart&action=addToCart&product=<?php echo $dato['ID'] ?>&productName=<?php echo $dato['SHORTDESCRIPTION'] ?>
                                                   &productPrice=<?php echo $dato['PRICE'] ?>&productImage=<?php echo $dato['URL'] ?>&productStock=<?php echo $dato['STOCK'] ?>&productPriceFinal=<?php echo $dato['PRECIOFINAL'] ?>" class="btn btn-primary">Comprar</a>
                                               <?php } else { ?>
                                                <span style="color:green"> <?php echo "Hay productos en stock"; ?></span>
                                                </small>
                                                <a href="index.php?controller=cart&action=addToCart&product=<?php echo $dato['ID'] ?>&productName=<?php echo $dato['SHORTDESCRIPTION'] ?>
                                                   &productPrice=<?php echo $dato['PRICE'] ?>&productImage=<?php echo $dato['URL'] ?>&productStock=<?php echo $dato['STOCK'] ?>&productPriceFinal=<?php echo $dato['PRECIOFINAL'] ?>" class="btn btn-primary">Comprar</a>
                                            <?php } ?>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>

                    <div class="pagination">
                      <nav aria-label="Page navigation example">
                        <ul class="pagination ">
                            <li class="page-item <?php if($pagina == 1){ ?> disabled <?php }?> "><a class="page-link" href="index.php?pagina=<?php echo ($pagina-1) ?>">Anterior</a></li>
                            <?php for ($pagina = 1; $pagina <= $numPaginas;$pagina++) { ?>
                          <li class="page-item"><a class="page-link" href="index.php?pagina=<?php echo $pagina ?>"><?php echo $pagina ?></a></li>
                           <?php }
                           if(empty($_GET['pagina'])){
                           }else{ ?>
                          <li class="page-item <?php if($_GET['pagina'] == $numPaginas){?> disabled <?php } ?>"><a class="page-link" href="index.php?pagina=<?php echo ($_GET['pagina'] +1) ?>">Siguiente</a></li>
                           <?php } ?>
                        </ul>
                      </nav>
                    </div>


        </body>

        <?php require_once("footer.phtml"); ?>

</html>
