<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title>Home</title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="css/home.css">
        <script src="views/filtros.js"></script>
    </head>
    <!-- Barra de navegacion -->
    <?php require_once("views/header.phtml");  ?>
    <body class="bg-secondary">

        <!-- Carousel -->
        <div class="container mt-2">
            <div class="row">
                <?php
                foreach ($orderedCategories as $id => $category) {
                    $catName = $category[0];
                    ?>
                    <div class="col-6 col-md-3 mb-2">
                        <div class="dropdown">
                            <button type="button" class="btn btn-block dropdown-toggle text-muted" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <a class="text-light" href="#"><?php echo $catName; ?></a>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="min-width:16rem;">

                                <?php
                                for ($i = 1; $i < count($category); $i++) {
                                    $idSubcategory = $category[$i]['ID'];
                                    $nameSubCategory = $category[$i]['NAME'];
                                    ?>
                                    <a class="dropdown-item" href="index.php?controller=products&action=viewCat&idSubcategory=<?php echo $idSubcategory ?>"><?php echo $nameSubCategory; ?></a>
                                    <?php
                                }
                                ?>
                            </div>

                        </div>
                    </div>
                    <?php
                }
                ?>
            </div>
        </div>

        <div class="container bg-secondary">
                  <!-- Filtros -->

            <div class="row">
              <div class="col-12 col-md-3">
                <div class="panel-group mt-3">
                  <div class="bg-dark text-center panel panel-default border rounded border-warning mb-3">
                    <div class="panel-heading">
                      <h4 class="panel-title">
                        <span class="text-light">Precio<a class="mr-2 float-right text-light" data-toggle="collapse" href="#precio"><i class="fa fa-caret-down" aria-hidden="true"></i></a></span>
                      </h4>
                    </div>
                    <div id="precio" class="panel-collapse collapse mb-2">
                      <div class="panel-body bg-secondary">
                          
                        <span>desde</span>
                        <input type="text" class="form-control" id="price-min" name="price-min" placeholder="min">
                        <span>hasta</span>
                        <input type="text" class="form-control" id="price-max" name="price-max" placeholder="max">

                        <a href="#" class="btn btn-success">Filtrar</a>
                      </div>
                    </div>
                  </div>
                  <div class="bg-dark text-center panel panel-default border rounded border-warning mb-3">
                    <div class="panel-heading">
                      <h4 class="panel-title">
                        <span class="text-light">Marcas<a class="mr-2 float-right text-light" data-toggle="collapse" href="#marcas"><i class="fa fa-caret-down" aria-hidden="true"></i></a></span>
                      </h4>
                    </div>
                    <div id="marcas" class="panel-collapse collapse">
                      <div class="panel-body bg-secondary text-left">
                        <?php foreach ($marcas as $marca) { ?>
                          <div class="form-check m-2">
                            <input class="form-check-input filtro" type="checkbox"  id="<?php echo $marca['BRAND'];?>">
                            <label class="form-check-label" for="defaultCheck1">
                              <?php echo $marca['NAME'] ?>
                            </label>
                          </div>
                        <?php } ?>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xs-12 col-md-9">
              <div class="row">
              <?php foreach ($datos as $dato) { 
                  ?>
                  
                  <div class="col-xs-12 col-md-6 col-lg-4">

                      <div class="card my-3" id="<?php echo $dato['BRAND']; ?>">
                           <a href="index.php?controller=products&action=viewPage&id=<?php echo $dato['ID']?>">
                               <img class="card-img-top zoom img-fluid" src="<?php echo $dato['URL'] ?> " alt="Card image">
                           </a>
                          <div class="card-body">
                              <p class="card-title"><strong><?php echo $dato['SHORTDESCRIPTION'] ?> </strong></p>
                              <?php if (empty($dato['DISCOUNTPERCENTAGE']))  { ?>
                                <p class="card-text text-center"><strong><?php echo $dato['PRICE'];?>€</strong></p>
                            <?php  }else{ ?>
                                <p class="card-text text-center">
                                    <span><strong><?php echo $dato['PRECIOFINAL'];?>€</strong></span>
                                    <span class="text-muted"><small><s><?php echo $dato['PRICE']; ?>€</s></small></span>
                                    <span class="badge badge-danger"><?php echo $dato['DISCOUNTPERCENTAGE'];?>%</span>
                                </p>

                          <?php  } ?>
                              <div class="card-footer text-center">
                                  <small> <?php if ($dato['STOCK'] == 0) { ?>
                                          <span style="color:red"> <?php echo "No quedan productos"; ?></span>
                                        </small>
                                        <a href="index.php?controller=cart&action=addToCart&product=<?php echo $dato['ID']?>&productName=<?php echo $dato['SHORTDESCRIPTION']?>
                                           &productPrice=<?php echo $dato['PRICE'] ?>&productImage=<?php echo $dato['URL']?>&productStock=<?php echo $dato['STOCK']?>" class="btn btn-primary disabled">Comprar</a>

                                      <?php } elseif ($dato['STOCK'] < 5) {
                                          ?>
                                          <span style="color:orange"> <?php echo "Quedan pocos en stock"; ?></span>
                                        </small>
                                        <a href="index.php?controller=cart&action=addToCart&product=<?php echo $dato['ID']?>&productName=<?php echo $dato['SHORTDESCRIPTION']?>
                                           &productPrice=<?php echo $dato['PRICE'] ?>&productImage=<?php echo $dato['URL']?>&productStock=<?php echo $dato['STOCK']?>" class="btn btn-primary">Comprar</a>
                                      <?php } else { ?>
                                          <span style="color:green"> <?php echo "Hay productos en stock"; ?></span>
                                        </small>
                                        <a href="index.php?controller=cart&action=addToCart&product=<?php echo $dato['ID']?>&productName=<?php echo $dato['SHORTDESCRIPTION']?>
                                           &productPrice=<?php echo $dato['PRICE'] ?>&productImage=<?php echo $dato['URL']?>&productStock=<?php echo $dato['STOCK']?>" class="btn btn-primary">Comprar</a>
                                      <?php } ?>

                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>
              </div>
              </div>
            </div>
        </div>

    </body>
    <footer class="mt-4">
        <div class="bg-primary py-3">
            <div class="container">
                <div class="row">
                    <div class="col-md-7">
                        <div class="row py-0">
                            <div class="col-sm-1 hidden-md-down">
                                <a class="bg-circle bg-info" href="#">
                                    <i class="fa fa-2x fa-fw fa-address-card" aria-hidden="true "></i>
                                </a>
                            </div>
                            <div class="col-sm-11 text-white">
                                <div><h4>  Contacto</h4>
                                    <p>   <span class="header-font">EGC</span>omponentes.com</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="d-inline-block">
                            <div class="bg-circle-outline d-inline-block" style="background-color:#3b5998">
                                <a href="https://www.facebook.com/"><i class="fa fa-2x fa-fw fa-facebook text-white"></i>
                                </a>
                            </div>
                            <div class="bg-circle-outline d-inline-block" style="background-color:#4099FF">
                                <a href="https://twitter.com/">
                                    <i class="fa fa-2x fa-fw fa-twitter text-white"></i></a>
                            </div>

                            <div class="bg-circle-outline d-inline-block" style="background-color:#0077B5">
                                <a href="https://www.linkedin.com/company/">
                                    <i class="fa fa-2x fa-fw fa-linkedin text-white"></i></a>
                            </div>
                            <div class="bg-circle-outline d-inline-block" style="background-color:#d34836">
                                <a href="https://www.google.com/">
                                    <i class="fa fa-2x fa-fw fa-google text-white"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/.footer-->
    <p class="text-center"> Copyright <i class="fa fa-copyright" aria-hidden="true"></i>
        EGComponentes 2018. Todos los derechos reservados. </p>
    <!--/.footer-bottom-->
    <div class="myModal">
        <?php include("views/login_view.phtml"); ?>
    </div>

</html>
