<div class="container" >

    <!-- The Modal -->
    <div class="modal fade" id="myModal">
        <div class="modal-dialog modal-lg ">
            <div class="modal-content">

                <!-- Modal body -->
                <div class="modal-body">
                    <div class="container nav-justified pt-4 pb-4">
                        <ul class="nav nav-tabs">
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="pill" href="#login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="pill" href="#registro">Registro</a>
                            </li>
                        </ul>
                    </div>

                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div class="tab-pane active container" id="login">
                            <form class="form-horizontal" role="form" method="POST" action="index.php?controller=login&action=login">
                                <div class="row">
                                    <div class="col-md-3"></div>
                                    <div class="col-md-6">
                                        <h2>Login</h2>
                                        <hr>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3"></div>
                                    <div class="col-md-6">
                                        <div class="form-group has-danger">
                                            <label class="sr-only" for="user">Usuario</label>
                                            <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                                <div class="input-group-addon iconBoot"><i class="fa fa-user"></i></div>
                                                <input type="text" name="user" class="form-control" id="userLogin" placeholder="usuario123" required autofocus>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-control-feedback">
                                            <span class="alert alert-danger align-middle invisible">

                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3"></div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="sr-only" for="password">Contraseña</label>
                                            <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                                <div class="input-group-addon iconBoot"><i class="fa fa-key"></i></div>
                                                <input type="password" name="password" class="form-control" id="passwordLogin" placeholder="Contraseña" required>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-control-feedback">
                                            <span class="alert alert-danger align-middle invisible">
                                                <!-- Put password error message here -->
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row" style="padding-top: 1rem">
                                    <div class="col-md-3"></div>
                                    <div class="col-md-6">
                                        <button type="submit" class="btn btn-success"><i class="fa fa-sign-in"></i> Login</button>
                                    </div>
                                </div>
                            </form>

                            <!-- Registro  -->
                        </div>
                        <div class="tab-pane container" id="registro">
                            <form class="form-horizontal" role="form" method="POST" id="submit" action="index.php?controller=login&action=register">
                                <div class="row">
                                    <div class="col-md-3"></div>
                                    <div class="col-md-6">
                                        <h2>Registro</h2>
                                        <hr>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3 field-label-responsive">
                                        <label for="name">Nombre Completo</label>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                                <div class="input-group-addon iconBoot"><i class="fa fa-user"></i></div>
                                                <input type="text" name="name" class="form-control" id="names" placeholder="Nombre Apellido" maxlength="50">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-control-feedback">
                                            <span class="alert alert-danger align-middle invisible" id="nameErr">

                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3 field-label-responsive">
                                        <label for="email">Dirección E-Mail</label>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                                <div class="input-group-addon iconBoot"><i class="fa fa-envelope" aria-hidden="true"></i></div>
                                                <input type="text" name="email" class="form-control" id="email" placeholder="correo@ejemplo.com" maxlength="50">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-control-feedback">
                                            <span class="alert alert-danger align-middle invisible" id="emailErr" >

                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3 field-label-responsive">
                                        <label for="email">Dirección</label>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                                <div class="input-group-addon iconBoot"><i class="fa fa-location-arrow" aria-hidden="true"></i></div>
                                                <input type="text" name="address" class="form-control" id="address" placeholder="C/Calle Num123" maxlength="100">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-control-feedback">
                                            <span class="alert alert-danger align-middle invisible" id="addressErr">
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3 field-label-responsive">
                                        <label for="email">Código Postal</label>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                                <div class="input-group-addon iconBoot"><i class="fa fa-map-marker" aria-hidden="true"></i></div>
                                                <input type="text" name="postalcode" class="form-control" id="postalcode" placeholder="ej- 07181">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-control-feedback">
                                            <span class="alert alert-danger align-middle invisible" id="postalcodeErr">
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3 field-label-responsive">
                                        <label for="email">Usuario</label>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                                <div class="input-group-addon iconBoot"><i class="fa fa-user"></i> </div>
                                                <input type="text" name="username" class="form-control" id="user" placeholder="usuario" maxlength="32">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-control-feedback">
                                            <span class="alert alert-danger align-middle invisible" id="userErr">
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3 field-label-responsive">
                                        <label for="password">Contraseña</label>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group has-danger">
                                            <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                                <div class="input-group-addon iconBoot"><i class="fa fa-key"></i></div>
                                                <input type="password" name="password" class="form-control" id="password" placeholder="Contraseña" maxlength="32" >
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-control-feedback">
                                            <span class="alert alert-danger align-middle invisible" id="passwordErr">
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3 field-label-responsive">
                                        <label for="password">Confirmar Contraseña</label>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                                <div class="input-group-addon iconBoot">
                                                    <i class="fa fa-repeat"></i>
                                                </div>
                                                <input type="password" name="passwordConfirmation" class="form-control" id="passwordConfirm" placeholder="Contraseña" maxlength="32">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-control-feedback">
                                            <span class="alert alert-danger align-middle invisible" id="passwordConfirmErr">
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <a class="btn btn-success" onclick="limpiar(),comprobar()" ><i class="fa fa-user-plus"></i>Registro</a>

                                </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>
