<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <title>Login</title>
  </head>
  <body>
    <div class="login">
      <form action="index.php?controller=login&action=login" method="post">
        <h1>Login</h1>
        Usuario:
        <input type="text" name="usuario">
        Contraseña:
        <input type="text" name="password">
        <input type="submit" name="login" value="Login">
      </form>
    </div>
  </body>
</html>
