<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8" />
        <title><?php echo $product['SHORTDESCRIPTION']?></title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" </script>
        <link rel="stylesheet" href="css/product.css">
    </head>
    <body class="bg-secondary">
     <!-- Barra de navegacion -->
<nav class="navbar navbar-expand-md navbar-light bg-primary sticky-top">
        <a class="navbar-brand mr-4" href="index.php">
            <img src="img/logo.svg" width="30" height="30" class="d-inline-block align-top" alt="">
            <span class="text-light">EGComponentes</span>
        </a>

        <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon "></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <form class="form-inline mx-auto" action="index.php?controller=products&action=search" method="POST">
                <input class="form-control mr-sm-2" type="search" name="buscador" placeholder="Search" aria-label="Search">
                <button class="btn btn-success my-2 my-md-0 mr-4" type="submit">Search</button>
            </form>

            <?php
            if (isset($_SESSION['usuario'])) {
                if ($_SESSION['usuario'] == "admin") {
                    ?>
                    <div class="dropdown mr-2">
                        <button class="btn bg-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-user-circle-o text-warning" aria-hidden="true"></i>
                            <span class="text-warning mr-4">Hola, <?php echo $_SESSION['usuario'] ?>  </span>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item bg-light" href="index.php?controller=products&action=addView">Afegir productes</a>
                            <a class="dropdown-item bg-light" href="index.php?controller=categories&action=add">Afegir categories</a>
                            <a class="dropdown-item bg-light" href="#">Crear promocions</a>
                            <a class="dropdown-item bg-light" href="index.php?controller=login&action=logout"><i class="fa fa-sign-out mr-2" aria-hidden="true"></i>Cerrar sesion</a>
                        </div>
                    </div>

                <?php } else { ?>
                    <div class="dropdown mr-2">
                        <button class="btn bg-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-user-circle-o text-warning" aria-hidden="true"></i>
                            <span class="text-warning mr-4">Hola, <?php echo $_SESSION['usuario'] ?>  </span>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a disabled class="dropdown-item bg-light" href="#">Editar perfil</a>
                            <a class="dropdown-item bg-light" href="#">Historial de compras</a>
                            <a class="dropdown-item bg-light" href="index.php?controller=login&action=logout">Cerrar sesion</a>
                        </div>
                    </div>
                    <?php
                }
            } else {
                ?>
                <button type="button" class="btn btn-warning mr-2" data-toggle="modal" data-target="#myModal">
                    Login/Register
                </button>"
            <?php } ?>

            <div>  <ul class="nav navbar-nav navbar-right">
                    <!-- Carrito de compra -->
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle text-light" data-toggle="dropdown" role="button" aria-expanded="false">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            <span class="badge badge-dark">4</span>
                            Carrito de compra<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-cart" role="menu">
                            <?php foreach ($_SESSION['cart'] as $carrito){ ?>
                            
                             <?php } if(empty($_SESSION['cart'])){?>
                            <p class="">No hay productos en el carrito</p>
                            <?php }else{ ?>
                                <li>
                                    <span class="item">
                                        <span class="item-left">
                                            <img class="imgCart" src="<?php echo $carrito['image']?>" alt="<?php echo $carrito['name']?>"/>
                                            <span class="item-info">
                                                <span><strong><?php echo $carrito['name']?></strong></span>
                                                <span class="text-muted">Cantidad: <?php echo $carrito['numUnits']?></span>
                                                <span> <kbd>Precio: <?php echo $carrito['price']?>€</kbd></span>
                                            </span>
                                        </span>
                                        <span class="item-right">
                                            <a href="index.php?controller=cart&action=deleteFromCart&product=<?php echo $carrito['id']?>"><button class="btn btn-danger  fa fa-close"></button></a>
                                        </span>
                                    </span>
                                </li>
                            <li class="divider"></li>
                            <li><a class="text-center" href="#">View Cart</a></li>
                        </ul>
                       <?php } ?>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
                <!-- Descripcion del producto -->
      <div class="container">
        <div class="row bg-light mt-2" style="height:1000px;">
          <div class="col-6 h-100 border">
              <img src="<?php echo $product['URL']?>" alt="producto" class="rounded imgProduct">
          </div>
          <div class="col-6 h-100 border ">
              <h3 class="mt-4 border"><?php echo $product['SHORTDESCRIPTION']?></h3>
              <div class="w-100"></div>
              <span class=""><strong>Descripción</strong></span>
              <p class="h-25 border border-dark"><?php echo $product['LONGDESCRIPTION']?> </p>
              <div class="w-100"></div>
              <p class="">Precio: <?php echo $product['PRICE']?>€</p>
              <div class="w-100"></div>
              <p class=""><?php
                if ($product['STOCK'] == 0) { ?>
                <span style="color:red"> <?php echo "No quedan productos"; ?></span>
                <?php
              } elseif ($product['STOCK'] < 5) { ?>
                    <span style="color:orange"> <?php echo "Quedan pocos productos en stock"; ?></span>
                  <?php } else{?>
                      <span style="color:green"> <?php echo "Hay productos en stock"; ?></span>
              </p>
            <?php } ?>
              <div class="w-100"></div>
              <span>Cantidad:</span> <input class="mb-4" type="number" value="1" min="1" max="<?php echo $product['STOCK']?>" id="number" style="width: 3em;">
              <div class="w-100"></div>
              <div class="row">
                <div class="col-6">
                  <button type="button" name="button" class="btn btn-primary btn-block btn-lg mt-2">Añadir al carrito</button>
                </div>
                <div class="col-6">
                  <button type="button" name="button" class="btn btn-primary btn-block btn-lg mt-2">Comprar</button>
                </div>
              </div>
          </div>
        </div>
      </div>
      <footer class="mt-4">
           <div class="bg-primary py-3">
          <div class="container">
            <div class="row">
              <div class="col-md-7">
                  <div class="row py-0">
                <div class="col-sm-1 hidden-md-down">
                    <a class="bg-circle bg-info" href="#">
                      <i class="fa fa-2x fa-fw fa-address-card" aria-hidden="true "></i>
                    </a>
                  </div>
                  <div class="col-sm-11 text-white">
                      <div><h4>  Contacto</h4>
                          <p>   <span class="header-font">EGC</span>omponentes.com</p>
                      </div>
                  </div>
                  </div>
              </div>
              <div class="col-md-5">
                <div class="d-inline-block">
                  <div class="bg-circle-outline d-inline-block" style="background-color:#3b5998">
                    <a href="https://www.facebook.com/"><i class="fa fa-2x fa-fw fa-facebook text-white"></i>
      		</a>
                  </div>
                  <div class="bg-circle-outline d-inline-block" style="background-color:#4099FF">
                    <a href="https://twitter.com/">
                      <i class="fa fa-2x fa-fw fa-twitter text-white"></i></a>
                  </div>

                  <div class="bg-circle-outline d-inline-block" style="background-color:#0077B5">
                    <a href="https://www.linkedin.com/company/">
                      <i class="fa fa-2x fa-fw fa-linkedin text-white"></i></a>
                  </div>
                  <div class="bg-circle-outline d-inline-block" style="background-color:#d34836">
                    <a href="https://www.google.com/">
                      <i class="fa fa-2x fa-fw fa-google text-white"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          </div>
      </footer>
          <!--/.footer-->
      <p class="text-center"> Copyright <i class="fa fa-copyright" aria-hidden="true"></i>
       EGComponentes 2018. Todos los derechos reservados. </p>
          <!--/.footer-bottom-->
    </body>
</html>
