<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8" />
        <title><?php echo $product['SHORTDESCRIPTION'] ?></title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" </script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="css/home.css">
</head>
<body class="bg-secondary">
    <!-- Barra de navegacion -->
    <?php require_once("views/header.phtml"); ?>
    <!-- Descripcion del producto -->
    <div class="container ">
        <div class="row bg-light mt-2">
            <div class="col-6 vistaContainer border">
                <img src="<?php echo $product['URL'] ?>" alt="producto" class="rounded imgProduct">
            </div>
            <div class="col-6 border">  
                <div class="mb-5"></div>

                <h3><strong><?php echo $product['SHORTDESCRIPTION'] ?></strong></h3>
                <div class="card">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Descripcion...
                    </button>

                    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                        <div class="card-body">
                            <p class="border border-dark h-50"><?php echo $product['LONGDESCRIPTION'] ?> </p>
                        </div>
                    </div>
                </div>
                <div class="w-100"></div>
                <?php if (empty($product['DISCOUNTPERCENTAGE'])) { ?>
                    <p class="card-text"><strong><?php echo $product['PRICE']; ?>€</strong></p>
                <?php } else { ?>
                    <p class="card-text">
                        <span><strong><?php echo $product['PRECIOFINAL']; ?>€</strong></span>
                        <span class="text-muted"><small><s><?php echo $product['PRICE']; ?>€</s></small></span>
                        <span class="badge badge-danger"><?php echo $product['DISCOUNTPERCENTAGE']; ?>%</span>
                    </p>

                <?php } ?>
                <div class="w-100"></div>
                <p class=""><?php if ($product['STOCK'] == 0) { ?>
                        <span style="color:red"> <?php echo "No quedan productos"; ?></span>
                    <?php } elseif ($product['STOCK'] < 5) {
                        ?>
                        <span style="color:orange"> <?php echo "Quedan pocos productos en stock"; ?></span>
                    <?php } else { ?>
                        <span style="color:green"> <?php echo "Hay productos en stock"; ?></span>
                    </p>
                <?php } ?>
                <div class="w-100"></div>
                <span>Cantidad:</span> <input class="mb-4" type="number" value="1" min="1" max="<?php echo $product['STOCK'] ?>" id="number" style="width: 3em;">
                <div class="w-100"></div>
                <?php if ($product['STOCK'] == 0) { ?>
                    <div class="row">
                        <div class="col-6">
                            <a href="" class="btn btn-primary btn-block btn-lg mt-2 disabled">Añadir al carrito</a>
                        </div>
                        <div class="col-6">
                            <a href="index.php?controller=cart&action=view" class="btn btn-primary btn-block btn-lg mt-2 disabled">Comprar</a>
                        </div>
                    </div>
                <?php } else { ?>
                    <div class="row">
                        <div class="col-6">
                            <a href="index.php?controller=cart&action=addToCart&product=<?php echo $product['ID'] ?>&productName=<?php echo $product['SHORTDESCRIPTION'] ?>
                               &productPrice=<?php echo $product['PRICE'] ?>&productImage=<?php echo $product['URL'] ?>&productStock=<?php echo $product['STOCK'] ?>&productPriceFinal=<?php echo $product['PRECIOFINAL'] ?>" class="btn btn-primary btn-block btn-lg mt-2">Añadir al carrito</a>
                        </div>
                        <div class="col-6">
                            <a href="index.php?controller=cart&action=addToCart&product=<?php echo $dato['ID'] ?>&productName=<?php echo $dato['SHORTDESCRIPTION'] ?>
                               &productPrice=<?php echo $dato['PRICE'] ?>&productImage=<?php echo $dato['URL'] ?>&productStock=<?php echo $dato['STOCK'] ?>&productPriceFinal=<?php echo $dato['PRECIOFINAL'] ?>" class="btn btn-primary btn-block btn-lg mt-2">Comprar</a>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</body>
<?php require_once("footer.phtml"); ?>
</html>
